name:                protolog
version:             0.1.0.0
github:              "madgen/protolog"
license:             BSD3
author:              "Mistral Contrastin"
maintainer:          "madgenhetic@gmail.com"
copyright:           "2022 Mistral Contrastin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madgen/protolog#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 1.3
- data-partition >= 0.3 && < 0.4
- fgl >= 5.7 && < 5.8
- transformers >= 0.5 && < 0.6
- graphviz >= 2999 && < 3000

library:
  source-dirs: src

tests:
  protolog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.8 && < 2.9
    - protolog
